repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        language_version: python3
        types: [python]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        additional_dependencies: [tomli]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
    -   id: prettier
        files: \.(md|yml|yaml)$

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-no-print-statement
    -   id: python-no-unicode-literals

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
