from setuptools import setup, find_packages

setup(
    name="enscrap",
    version="0.1.0",
    description="Multi-agent AI system for enriching school data",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "supabase>=2.0.0",
        "requests>=2.31.0",
        "beautifulsoup4>=4.12.2",
        "python-dotenv>=1.0.0",
        "psycopg2-binary>=2.9.3",
        "lru_cache>=0.2.3",
        "retrying>=1.3.3",
        "tenacity>=8.2.3",
        "pydantic>=2.5.3",
        "aiohttp>=3.9.1",
        "asyncio>=3.4.3",
        "aiofiles>=23.2.1",
        "python-multipart>=0.0.6",
        "numpy>=1.24.3",
        "pandas>=2.0.3",
        "geopy>=2.4.0",
        "python-dateutil>=2.8.2",
        "scikit-learn>=1.3.0",
        "scipy>=1.11.1",
        "shapely>=2.0.1",
        "geopandas>=0.13.2",
        "pyarrow>=14.0.1",
        "fastparquet>=2023.11.0",
        "boto3>=1.29.0",
        "azure-storage-blob>=12.18.0",
        "pymongo>=4.5.0",
        "redis>=5.0.1",
        "elasticsearch>=8.10.1",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.3",
            "pytest-asyncio>=0.21.1",
            "pytest-cov>=4.1.0",
            "black>=23.11.0",
            "isort>=5.12.0",
            "mypy>=1.6.1",
            "flake8>=6.1.0",
            "pre-commit>=3.5.0"
        ]
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
